version: '3'

services:
  backend:
    build: .
    container_name: bookingai-backend
    env_file: .env
    ports:
      - "5002:5002"
    restart: always

  frontend:
    build: ./client
    container_name: bookingai-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always 